### ISSUE TITLE
Launching a newly created instance failed

### ISSUE THREAD

**Issue by fprevost** [bxforce/bnc-eth#1]
Launching of my newly created instance failed with the following stack trace :

`2020/06/22 08:26:11 Start hub (waiting for 1 validators)2020/06/22 08:26:13 Enroll as validator=true org1 : 0x1005388E1649240036d199B6ad71EafC0164edAd with localhost:80802020/06/22 08:26:13 New validator: 0x1005388E1649240036d199B6ad71EafC0164edAd2020/06/22 08:26:13 Broadcast genesis & topology2020/06/22 08:26:13 Genesis 'aura-network' and 0 peers received2020/06/22 08:26:13 Close hub2020/06/22 08:26:13 /usr/local/bin/parity --base-path /chain/data/parity --config /chain/data/config.toml --engine-signer 0x1005388E1649240036d199B6ad71EafC0164edAd --author 0x1005388E1649240036d199B6ad71EafC0164edAd --no-discovery --identity org1 --bootnodesLoading config file from /chain/data/config.toml2020-06-22 08:26:13 UTC Running AuRa with a single validator implies instant finality. Use a database?2020-06-22 08:26:13 UTC Starting Parity-Ethereum/v2.7.2-stable-2662d19-20200206/x86_64-unknown-linux-gnu/rustc1.41.02020-06-22 08:26:13 UTC Keys path /chain/data/parity/keys/aura-network2020-06-22 08:26:13 UTC DB path /chain/data/parity/chains/aura-network/db/1d4e63e289d6c1762020-06-22 08:26:13 UTC State DB configuration: fast2020-06-22 08:26:13 UTC Operating mode: active2020-06-22 08:26:13 UTC Moved 1 keys from /chain/data/parity/keys to /chain/data/parity/keys/aura-network2020-06-22 08:26:13 UTC Not preparing block; cannot sign.2020-06-22 08:26:14 UTC Not preparing block; cannot sign.2020-06-22 08:26:14 UTC Configured for aura-network using AuthorityRound engine2020-06-22 08:26:14 UTC Removed existing file '/chain/data/parity/jsonrpc.ipc'.`

I checkout the previous commit. It works fine.

**Comment by nheulot** [comment]
There was indeed a bug in the init sequence. It has been fixed in the new commit e05cdd0f22d4bf6f590bf7ab995e1d6c8eedb214.

**Comment by fprevost** [comment]
Thanks. I'll try to recreate my node.

**Comment by fprevost** [comment]
I've switch back to use directly your master branch and it works fine. Thanks
